resources:
- name: repo
  type: git
  icon: gitlab
  source:
    uri: https://github.com/concourse/examples.git

- name: github
  type: git
  icon: github
  check_every: 10s
  source:
    uri: https://github.com/Rumb0/concourse-tests.git


jobs:
- name: set-self
  plan:
  - get: github
    trigger: true
  - set_pipeline: self
    file: github/ci/pipelines/main.yml

- name: hello-windows-job
  plan: 
  - get: repo
  - get: github
    passed: [set-self]
    trigger: true
  - task: hello-world-task
    config:
      platform: windows
      inputs:
      - name: repo
      - name: github
      params:
        TEST_VAR: VALUE_OF_TEST_VAR
        TEST_VAR2: VALUE_OF_TEST_VAR2
      run:
        path: bash
        args: [ "github/ci/scripts/build.sh" ]


- name: hello-linux-job
  plan:
  - get: github
    passed: [set-self]
    trigger: true
  - get: repo
  - task: hello-world-task
    config:
      platform: linux
      inputs:
      - name: repo
      - name: github
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
      params:
        TEST_VAR: VALUE_OF_TEST_VAR
        TEST_VAR2: VALUE_OF_TEST_VAR2
      run:
        path: bash
        args: [ "github/ci/scripts/build.sh" ]
